### ISSUE TITLE
Regex: match multiple lines

### ISSUE THREAD

**Issue by EntityReborn** [killjoy1221/TabbyChat-2#113]
One server I participate in spams broadcasts every 10 minutes, the first and last lines are dash (----) characters.
Is there a way to redirect the entire chunk of lines to another tab/channel? Typically 4 to 6 lines in total.

**Comment by mattmess1221** [comment]
Sure. Create a new filter with the following settings:

Regex option (.* button): Enabled
Pattern: `^----.+----$`
Destination: `server`

^ means the beginning, $ means the end.

**Comment by EntityReborn** [comment]
This will filter against the following?
![image](https://user-images.githubusercontent.com/678249/76274300-7b564580-623d-11ea-8980-331ddf44cf92.png)
I am familiar with regex in general, just not sure how Tabby parses messages.

**Comment by mattmess1221** [comment]
Oh. That will be tougher to detect. Right now, messages are filtered one at a time, and they're stateless.  I don't see a way of doing this reliably. Since other messages theoretically could be sent before the last ending, I don't want to risk filtering something that wasn't meant to. Not to mention if you mess up the filter (or the server messes up the message), you'll lose all the messages!

**Comment by EntityReborn** [comment]
Fair enough.
