### ISSUE TITLE
Cannot filter msges

### ISSUE THREAD

**Issue by tyler489** [killjoy1221/TabbyChat-2#68]
i would like to filter out msges starting with [RCBroadcast] and [RC Cash] but it is also filting out all the ranks on the server as seperate tabs... and it removes them from the main stream considering there are 10 ranks thats 10 chats to go though http://pastebin.com/1vLH3rEQ

**Comment by killjoy1221** [comment]
I don't think you fully understand regex. Most characters are WYSIWYG, but
there are many which have special meaning. For example, anything inside of
[] will match any of the characters inside. You'll need to escape them
using the backslash.

You can find tutorials on regex online.

I think I'll make regex an opt in feature of filters later. Maybe a few
other flags as well.

**Comment by tyler489** [comment]
OK So if i wanted to find [RCBroadcast] or [RC Cash] what would i do
my mind is blown

**Comment by killjoy1221** [comment]
Don't leave the `a^` in the box. That's just a dummy pattern that will never match anything.

Anyway, I think your issue is that by default, [] represents a channel. If I understand what you are saying, your ranks are denoted by `[RANK] Player: Message`. Correct? You will want to select the correct delimiters from the server settings for channels.

As for your regex, the best solutions are often the simplest.

`^\[RC(?:Broadcast| Cash)\].*`

**Breakdown**

- `^` Represents the start of a line
- `[ ]` Matches any character inside
- `\` escapes any special character, allowing it to be used literally`
- `( )` Represents an arbitrary group
- `?:` Non-capturing group
- `|` Matches either side
- `.` Matches any character
- `*` Matches zero or more of the previous token

**Comment by tyler489** [comment]
yes [Rankname] Playername: MSG
and the msges i want to filter are  https://gyazo.com/7b6ed0d2d8606f5928e460d641323810 and

**Comment by killjoy1221** [comment]
Read the rest of my reply. The pattern you need is in there.

**Comment by tyler489** [comment]
Yes I read it but didn't get around to testing

**Comment by tyler489** [comment]
Need help again i want to block out this MSG **ENEMY BLEEDING** What regex would i want

i get that * is a spectial charater
^\[**Enemy Bleeding**\] Didnt seem to work

**Comment by killjoy1221** [comment]
I suggest using a site such as http://regexr.com

**Comment by tyler489** [comment]
alright cant seem to figure it out

**Comment by tyler489** [comment]
^(\*\*Enemy Bleeding(\**)) Works in the filter to find **Enemy Bleeding**
but in game it doesnt do it

**Comment by killjoy1221** [comment]
Refer to the special characters. What does `*` mean?

**Comment by tyler489** [comment]
^(\*\*Enemy Bleeding(\**))
this works in the RegExr but not in game

**Comment by tyler489** [comment]
oh im stupid.... how do i ignore case

**Comment by killjoy1221** [comment]
There's a botton for that in the latest version. Otherwise, it's
impossible.
